export const USER_ADD = 'USER_ADD'
export const USER_EDIT = 'USER_EDIT'
export const USER_DELETE = 'USER_DELETE'
export const USER_FILTER = 'USER_FILTER'
export const USER_START_OPERATE = 'USER_START_OPERATE'
